### PR TITLE
Pin dependencies matching Ritvik's virtual environment

### LINKED ISSUE #8: Publish pinned dependencies in addition to pyproject.toml
For future reproducibility, we should publish the exact dependency versions used for the paper, as a `requirements.txt` and/or `pdm.lock` file.

### PR DESCRIPTION
**Pull request by pgarrison**
# Context
Closes #8.

This PR works as follows.
* PDM generates a `pdm.lock` file from the `pyproject.toml`, and the particular dependencies in this lock file have been specifically selected to match Ritvik's virtual environment as closely as possible (see the `pip freeze` output in #8).
* PDM exports the `pdm.lock` file to a `requirements.txt` file for conda and pip users.

# Differences from Ritvik's virtual environment
* `scipy` was downgraded from `1.9.3` to `1.8.1` for compatibility with other packages.
* `questionary` was downgraded from `2.0.1` to `1.10.0` for compatibility with other packages.
* A couple Windows-specific libraries were added (waitress, pywin32, pyreadline3, jinxed, and ansicon)
* Added `exceptiongroup` (required by lightning)
* `setuptools` was added
* Many dependencies were removed, including `ipython`. These are dependencies that were not needed by any of the packages declared in the `pyproject.toml`. Hopefully the are not needed by the code.

# Potential issues
* The `requirements.txt` exported by pdm cannot be pip-installed due to `torch-scatter`'s poorly-managed build-time dependency on `torch`. As a first pass, this PR addresses it in a manual way that I don't really like:
  - Moved `torch-scatter` out of `requirements.txt` manually and added it to a `requirements2.txt` (see installation instructions in README.md).
  - Since the default torch-scatter on PyPi installs from source it is very slow. Since I was already manually editing the requirements.txt, I went ahead and added an instruction to install the pre-built binary from the torch website.

# TO DO
* Evaluate license compatibility
* Figure out if ipython or other packages need to be added back (check all the import statements)

# Testing
Just `import pointcloudutils`, and `import br`.

### CODE REVIEW

**Review by ritvikvasan — APPROVED** [review]
Looks good to me. I can try out this env going forward

**Comment by fatwir** [comment]
For the loggers to work well, pip will also be required as a dependency in the pyproject.toml file. Also, when I tried to run some of the notebooks, ipykernel>=6.29.5 worked for me (maybe we could add this to the .toml file as well!). And, for the preprocessing scripts to work well,  "PyOpenGL>=3.1.0" and "PyOpenGL-accelerate>=3.1.7" will also be required (but I guess this comes under the additional dependencies since I am not sure if everyone would want to run the preprocessing files too!) - @ritvikvasan can you confirm this?

**Comment by ritvikvasan** [comment]
I tried creating a new virtual env and running the install instructions here. Im getting this error when trying to install lie-learn. I did set a TMPDIR to avoid the permissions issue. Any ideas?

`Collecting lie-learn==0.0.1.post1 (from -r requirements2.txt (line 104))
  Using cached https://artifactory.corp.alleninstitute.org/artifactory/api/pypi/pypi-virtual/packages/packages/14/6b/a0660174724902ecff31adf58c766e698a5a0a2a187ca1666432a0be4c90/lie_learn-0.0.1.post1.tar.gz (14.7 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      <string>:19: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!

              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************

      !!
      /allen/aics/modeling/ritvik/projects/36_br_env/.venv/bin/python: No module named pip`

**Comment by fatwir** [comment]
I think this could point to the comment I had added too. "pip" would need to be added as one of the dependencies in the .toml file.

**Comment by pgarrison** [comment]
> I tried creating a new virtual env and running the install instructions here. Im getting this error when trying to install lie-learn. I did set a TMPDIR to avoid the permissions issue. Any ideas?
> 
> ```
> Collecting lie-learn==0.0.1.post1 (from -r requirements2.txt (line 104))
>   Using cached https://artifactory.corp.alleninstitute.org/artifactory/api/pypi/pypi-virtual/packages/packages/14/6b/a0660174724902ecff31adf58c766e698a5a0a2a187ca1666432a0be4c90/lie_learn-0.0.1.post1.tar.gz (14.7 MB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
> 
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [50 lines of output]
>       <string>:19: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
>       !!
> 
>               ********************************************************************************
>               Requirements should be satisfied by a PEP 517 installer.
>               If you are using pip, you can try `pip install --use-pep517`.
>               ********************************************************************************
> 
>       !!
>       /allen/aics/modeling/ritvik/projects/36_br_env/.venv/bin/python: No module named pip
> ```

What commands did you run? I was able to do the following (without using `--no-build-isolation`), even after clearing `pip`'s cache.

```bash
pip install -r requirements1.txt
pip install -r requirements2.txt
```

**Comment by pgarrison** [comment]
> I tried creating a new virtual env and running the install instructions here. Im getting this error when trying to install lie-learn. I did set a TMPDIR to avoid the permissions issue. Any ideas?
> 
> ```
> Collecting lie-learn==0.0.1.post1 (from -r requirements2.txt (line 104))
>   Using cached https://artifactory.corp.alleninstitute.org/artifactory/api/pypi/pypi-virtual/packages/packages/14/6b/a0660174724902ecff31adf58c766e698a5a0a2a187ca1666432a0be4c90/lie_learn-0.0.1.post1.tar.gz (14.7 MB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
> 
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [50 lines of output]
>       <string>:19: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
>       !!
> 
>               ********************************************************************************
>               Requirements should be satisfied by a PEP 517 installer.
>               If you are using pip, you can try `pip install --use-pep517`.
>               ********************************************************************************
> 
>       !!
>       /allen/aics/modeling/ritvik/projects/36_br_env/.venv/bin/python: No module named pip
> ```

@ritvikvasan What commands did you run? I was able to do the following (without using `--no-build-isolation`), even after clearing `pip`'s cache.

```bash
pip install -r requirements1.txt
pip install -r requirements2.txt
```

**Comment by pgarrison** [comment]
> For the loggers to work, "pip" will also be required as a dependency in the pyproject.toml file. Also, when I tried to run some of the notebooks, "ipykernel>=6.29.5" worked for me (maybe we could add this to the .toml file as well!). And, for the preprocessing scripts to work well, "PyOpenGL>=3.1.0" had to be added in the last version of the .toml file, but after I installed the latest set of dependencies, it looked like PyOpenGL was installed in the list of dependencies (not sure if this is a dependency for one of the packages that we install)!

Done

**Comment by ritvikvasan** [comment]
ok I tried running it again, but this time I explicitly set the `PIP_CACHE_DIR` and it seems to be working okay now!

**Comment by fatwir** [comment]
There are a few differences in the config files that I noticed (https://github.com/AllenCell/benchmarking_representations/blob/pdm/configs/data/pcna/image.yaml), especially in the path parameter. I think it will be good to merge from main and then merge this PR!

**Pull request merged**
