### PR TITLE
add csv logger to all experiments

### PR DESCRIPTION
**Pull request by ritvikvasan**
Changes - 

1. Replace mlflow with csv logger everywhere as a default. Save checkpoints and outputs to local paths. 
2. Specify unique name for each experiment. "name" flag associated with CSVLogger
3. Add missing experiments for some datasets (e.g. Classical image experiment for cell pack data)

### CODE REVIEW

**Comment by pgarrison** [comment]
There are a couple references to `mlflow` in the docs that should be removed.

**Comment by pgarrison** [comment]
Closes #18

**Comment by pgarrison** [comment]
So did #31 migrate just some of the experiments to the CSV logger, and this PR is for migrating the rest?

**Comment by fatwir** [comment]
There are multiple experiments with the same name. As an example "so3_seg" is the name for 3 experiments. I think affixing the experiment name before the model_name can solve this!

**Comment by ritvikvasan** [comment]
I think #31 just didn't create any experiment specific names. So every experiment would have saved to the exact same local folder

**Comment by fatwir** [comment]
> So did #31 migrate just some of the experiments to the CSV logger, and this PR is for migrating the rest?
> I think #31 just didn't create any experiment specific names. So every experiment would have saved to the exact same local folder

Earlier, a`csv.yaml` file was introduced within the [configs/logger](https://github.com/AllenCell/benchmarking_representations/tree/main/configs/logger) directory. This file made it possible to use a CSV logger by adjusting the logger settings through overrides.

In the current pull request (PR), Ritvik has enhanced the functionality of the CSV logger, allowing to save the experiment's name and specify an output directory for the logged data.

**Comment by ritvikvasan** [comment]
@fatwir saving each experiment to a separate folder. Thanks for noticing that

**Review by fatwir — APPROVED** [review]
lgtm!

**Review by pgarrison — APPROVED** [review]
> > So did #31 migrate just some of the experiments to the CSV logger, and this PR is for migrating the rest?
> > I think #31 just didn't create any experiment specific names. So every experiment would have saved to the exact same local folder
> 
> Earlier, a`csv.yaml` file was introduced within the [configs/logger](https://github.com/AllenCell/benchmarking_representations/tree/main/configs/logger) directory. This file made it possible to use a CSV logger by adjusting the logger settings through overrides.
> 
> In the current pull request (PR), Ritvik has enhanced the functionality of the CSV logger, allowing to save the experiment's name and specify an output directory for the logged data.

I think I still don't understand why we had configs like this:
```yaml
logger:
  mlflow:
```
But I think the change seems appropriate.

**Comment by ritvikvasan** [comment]
I think that was a bug and it shouldn't have been there when we switched to csv

**Pull request merged**
