### PR TITLE
Add dependencies for image preprocessing to virtual environment and installation instructions

### LINKED ISSUE #17: Write instructions for installing image_preprocessing/pyproject.toml dependencies
Currently there are two `pyproject.toml` files for two different virtual environments, ~but ideally we'd only have a single virtual environment.~

See comments below. New goal is to document how to install the second environment, with a lockfile.

### PR DESCRIPTION
**Pull request by pgarrison**
# Purpose
Running preprocessing code should be simple: ideally the same installation steps used for the rest of the project would also set up an environment usable for preprocessing.

We should publish a lockfile that includes dependencies for preprocessing so that that part of the analysis is also reproducible.

Closes #17

# Changes
* Move `src/br/data/preprocessing/image_preprocessing` to `subpackages/image_preprocessing`
* Loosen the constraints on `image_preprocessing`'s dependencies, because the `^` constraints conflict with the main dependencies.
* Update instructions and pyproject.toml to install `image_preprocessing` and its dependencies

# Testing
* Installed via `pdm` and `pip` and ran the automated tests in each.
* [x] Added a test that imports `image_preprocessing` and tested it against both `pdm` and `pip` installation methods

### CODE REVIEW

**Review by ritvikvasan — APPROVED** [review]
Amazing! Just installed everything via pip, and the tests work. Thanks @pgarrison !

**Comment by fatwir** [comment]
I get this error when I try to install the env
`pdm.exceptions.BuildError: Build backend raised error: Module 'Cython' is missing, please make sure it is specified in the 'build-system.requires' section. If it is not possible, add it to the project and use '--no-isolation' option.
Showing the last 10 lines of the build output:
  File "/allen/aics/assay-dev/users/Fatwir/benchmarking_representations/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 420, in build_wheel
    return self._build_with_temp_dir(
  File "/allen/aics/assay-dev/users/Fatwir/benchmarking_representations/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 402, in _build_with_temp_dir
    self.run_setup()
  File "/allen/aics/assay-dev/users/Fatwir/benchmarking_representations/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 502, in run_setup
    super().run_setup(setup_script=setup_script)
  File "/allen/aics/assay-dev/users/Fatwir/benchmarking_representations/.venv/lib/python3.10/site-packages/setuptools/build_meta.py", line 318, in run_setup
    exec(code, locals())
  File "<string>", line 9, in <module>
ModuleNotFoundError: No module named 'Cython'`

**Review by fatwir — CHANGES_REQUESTED** [review]
I think a `pdm add cython` and `pdm add poetry`  should fix stuff - I will try doing this to see if it works!

**Comment by fatwir** [comment]
I successfully managed to install the environment using PDM. Here’s the relevant `git diff` for the `pyproject.toml` files:

```diff
+    "cython>=3.0.11",
+    "poetry>=1.8.4",
```

I added these two dependencies to the list, which allowed me to install everything without issues! I even ran a test for the `image_preprocessing` script (with a modified version of the variance dataset), and that ran smoothly.

However, to ensure completeness, I also attempted model training by running the following command:

```bash
python /src/br/models/train.py experiment=npm1_perturb/image_sdf_classical ++trainer.min_epochs=1 ++trainer.max_epochs=2
```

 Unfortunately, this resulted in an error: 

```
No module named 'lie_learn.representations.SO3.irrep_bases'
```


To troubleshoot, I reverted to an earlier version of the environment from a previous PDM installation and executed:

```python
python -c "import lie_learn.representations.SO3.irrep_bases"
```

This worked just fine, so I'm not sure what the issue is (probably it could be related to relaxing some of the dependencies?)

**Comment by pgarrison** [comment]
It seems we have a bit of a conundrum.

* We need to build `py3nj` and `torch-scatter` with `--no-isolation`
* `image_preprocessing` depends on `datrie` which has a build-time dependency on `Cython`
* `lie-learn==0.0.1.post1` installs incorrectly (without the `irrep_bases` module) if `Cython` is present at build time (I believe that's related to [this configuration](https://github.com/AMLab-Amsterdam/lie_learn/blob/5bd1a62da3573a0b04eabee0df179fe39b0ea8be/setup.py#L7-L12))

Some possible fixes:
* Upgrade `lie-learn` to `0.0.2`. But it seems like this version may be very different from `0.0.1.post1`: they were published 4 years apart.
* Stick with two different environments for `image_preprocessing` and the rest of the project (I'm leaning toward this at the moment)
* Work on installing `py3nj` and `torch-scatter` without `--no-isolation`. I'm doubtful this will work, mainly due to `py3nj`. It may require upgrading `py3nj`, which again gets us into uncharted territory.

**Comment by pgarrison** [comment]
I believe the latest versions of `py3nj` (0.2.1) and `lie-learn` (0.0.2) would be much easier to install: `py3nj` can install without `--no-isolation` (I believe it now properly specifies its build-time dependencies), and `lie-learn` can be installed with `Cython` present at build time and still install `lie_learn.representations.SO3.irrep_bases` properly.

For future projects, I strongly recommend upgrading these dependencies. Since our current goal is to reproduce Ritvik's work, I think we should go with two separate virtual environments.

**Pull request closed without merging**
